# Generated by Django 4.1.3 on 2022-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_alter_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
